// Auto-generated dataset for Senior Batch 2025-27
const INITIAL_BATCH_DATA = [
    {
        "id":  1,
        "name":  "Veer pratap singh",
        "email":  "pg25veer.pratap.singh@isbm.ac.in",
        "pgEmail":  "pg25veer.pratap.singh@isbm.ac.in",
        "mobile":  "8857012764",
        "rollNo":  "MNP20251121",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  64.8,
        "perc12":  58.2,
        "percGrad":  75,
        "gradStreamRaw":  "Commerce ",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Propedge Realty",
        "internship1Role":  "Business development intern",
        "internship1Duration":  "2 MONTHS",
        "internship2Company":  "Aditya birla capital",
        "internship2Role":  "Marketing intern",
        "internship2Duration":  "3 months",
        "numInternships":  2,
        "certifications":  "Product management \nSales management \nAccounting from beginner to advanced",
        "softSkills":  "Communication Skills\n    Adaptability \u0026 Learning\n    Leadership \u0026 Initiative     \nProblem-Solving    \n Team Collaboration",
        "cvLink":  "https://drive.google.com/open?id=12Ob2XpX7LhJsYppTjVOBFCgkC2aCu6l5"
    },
    {
        "id":  2,
        "name":  "Motasim Waqas",
        "email":  "pg25motasim.waqas.ansari@isbm.ac.in",
        "pgEmail":  "pg25motasim.waqas.ansari@isbm.ac.in",
        "mobile":  "9305477697",
        "rollNo":  "MNP20251061",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  79.8,
        "perc12":  87.6,
        "percGrad":  76.29,
        "gradStreamRaw":  "Commerce",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  24,
        "workExpRaw":  "2 years",
        "prevJobRole":  "Foreman - Sales at Lucknow Metals",
        "internship1Company":  "TRUST Mutual Fund",
        "internship1Role":  "RETAIL SALES INTERN",
        "internship1Duration":  "1.5 months",
        "internship2Company":  "Noor Tech and Feb",
        "internship2Role":  "Assistant – Quality Control",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "\tForward by McKinsey (2026)\n\tTechnical SEO by SEMrush (2026)\n\tGoogle Analytics 4 (2026)\n\tHubSpot Social Media (2026)     \n\tDigital Marketing Channels by Unilever (2026)\n\tExcel by Infosys Springboard (2025)\n\tArtificial Intelligence V2 by IBM (2025)",
        "softSkills":  "Communication, Sales, Public Presentation",
        "cvLink":  "https://drive.google.com/open?id=1aOmymNDUGL-wJmHNp0FLCHeD2rJIs7s3"
    },
    {
        "id":  3,
        "name":  "Anurag kumar",
        "email":  "pg25anurag.kumar@isbm.ac.in",
        "pgEmail":  "pg25anurag.kumar@isbm.ac.in",
        "mobile":  "8271272197",
        "rollNo":  "MDP20255007",
        "gender":  "Male",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  60.5,
        "perc12":  59.83,
        "percGrad":  76.56,
        "gradStreamRaw":  "Marketing ",
        "gradStream":  "Other",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "F2 fintech",
        "internship1Role":  "Management Trainee- Financial Sales Intern",
        "internship1Duration":  "4 Months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Mutual fund distributor\nMS Excel",
        "softSkills":  "Communication Skills\nNegotiation \u0026 Persuasion\nProblem-Solving\nAdaptability\nTime Management\nActive Listening\nTeamwork \u0026 Collaboration\nLeadership",
        "cvLink":  "https://drive.google.com/open?id=1LI2ODg5xnajhOzpe50jJ6FkczGtdBNm5"
    },
    {
        "id":  4,
        "name":  "Andani Sandhya",
        "email":  "pg25sandhya.andani@isbm.ac.in",
        "pgEmail":  "pg25sandhya.andani@isbm.ac.in",
        "mobile":  "9023708042",
        "rollNo":  "MBP20251013",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  77.33,
        "perc12":  61.73,
        "percGrad":  77.9,
        "gradStreamRaw":  "Commerce ",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Workstore",
        "internship1Role":  "SEO- Digital Marketing",
        "internship1Duration":  "3.0",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Six -Sigma Green Belt \nMaster AI-powered SEO Fundamental\nMarketing Analytics (Pursuing)\nMaster Facebook Ads with AI\nGoogle Analytics",
        "softSkills":  "Teamwork and Collaboration\nAdaptability\nTime Management\nCritical Thinking\nProblem- Solving\nStorytelling with Data",
        "cvLink":  "https://drive.google.com/open?id=1OPbvUbrDlCVlXts4tHamkmmxZAIAltI2"
    },
    {
        "id":  5,
        "name":  "Esha Jaiswal",
        "email":  "pg25esha.jaiswal@isbm.ac.in",
        "pgEmail":  "pg25esha.jaiswal@isbm.ac.in",
        "mobile":  "7004247462",
        "rollNo":  "MNP20251041",
        "gender":  "Female",
        "section":  "B",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  75,
        "perc12":  84,
        "percGrad":  70,
        "gradStreamRaw":  "Commerce ",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Solenis",
        "internship1Role":  "Marketing and Business Development",
        "internship1Duration":  "2.0",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Digital Marketing and GA4 Certification",
        "softSkills":  "Leadership, Communication, Teamwork, Adaptability, Problem-Solving, Time Management, Coordination, Initiative, Responsibility, Creativity, Empathy, and Attention to Detail.",
        "cvLink":  "https://drive.google.com/open?id=1-aeeIX2sddm4D6HcvHfntPDHKg_Q4OMg"
    },
    {
        "id":  6,
        "name":  "Sakshi Dinesh Mohod",
        "email":  "pg25sakshi.mohod@isbm.ac.in",
        "pgEmail":  "pg25sakshi.mohod@isbm.ac.in",
        "mobile":  "8999948625",
        "rollNo":  "MDP20255041",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  86,
        "perc12":  80,
        "percGrad":  83,
        "gradStreamRaw":  "Commerce",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Bajaj Life Insurance",
        "internship1Role":  "Marketing Intern",
        "internship1Duration":  "6 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "1. Digital Marketing \n2. Social Media Marketing\n3. Graphics \u0026 Video Editing \n4. MS Excel \u0026 PowerPoint",
        "softSkills":  "1. Communication Skills\n2. Teamwork \u0026 Collaboration\n3. Problem-Solving\n4. Adaptability \u0026 Learning Agility\n5. Stakeholder \u0026 Client Management",
        "cvLink":  "https://drive.google.com/open?id=19LWqJo6K5UyDsYc6AzOpa1BjCKsTg-C4"
    },
    {
        "id":  7,
        "name":  "Abhishek Roshan Bhandari",
        "email":  "pg25abhishek.bhandari@isbm.ac.in",
        "pgEmail":  "pg25abhishek.bhandari@isbm.ac.in",
        "mobile":  "8625005504",
        "rollNo":  "MNP20252005",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  87.4,
        "perc12":  67.5,
        "percGrad":  82.65,
        "gradStreamRaw":  "Commerce (BBA)",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Burger King",
        "internship1Role":  "Operations and market survey",
        "internship1Duration":  "2 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Fundamental of digital marketing",
        "softSkills":  "Communication \nProblem solving",
        "cvLink":  "https://drive.google.com/open?id=1NAACs3pVK9nHMbcwGmZAuX8B9yT1EUcq"
    },
    {
        "id":  8,
        "name":  "Dhruv Nileah Vaidya",
        "email":  "pg25dhruv.vaidya@isbm.ac.in",
        "pgEmail":  "pg25dhruv.vaidya89@gmail.com",
        "mobile":  "9879866606",
        "rollNo":  "MDP20255010",
        "gender":  "Male",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  93,
        "perc12":  91,
        "percGrad":  71,
        "gradStreamRaw":  "B.com",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  2,
        "workExpRaw":  "2 months",
        "prevJobRole":  "",
        "internship1Company":  "Burger King",
        "internship1Role":  "Business and opeartions development role",
        "internship1Duration":  "2 months",
        "internship2Company":  "Burger King",
        "internship2Role":  "Bussiness and operations development",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  " Basics of event Management(S.D.J International college-2021)\n MS Office(beginner)",
        "softSkills":  "Communication skills\nExcel (beginner)\nBasic MS office\nDecision Making\nLeadership skills\nTeam work\nProblem-solving\nAbilities",
        "cvLink":  "https://drive.google.com/open?id=1Qg2FcPNDIzR3_tP3_yYvvEIZiQLT4NM6"
    },
    {
        "id":  9,
        "name":  "Mahim Jain",
        "email":  "pg25mahim.jain@isbm.ac.in",
        "pgEmail":  "pg25mahim.jain@isbm.ac.in",
        "mobile":  "9351208787",
        "rollNo":  "MDP20255017",
        "gender":  "Male",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  78,
        "perc12":  78,
        "percGrad":  66,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  0,
        "workExpRaw":  "",
        "prevJobRole":  "",
        "internship1Company":  "Godrej Properties",
        "internship1Role":  "CRM intern",
        "internship1Duration":  "2.0",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "MS Excel By Udemy\nAWS SoluƟons Architecture Job \nSimulaƟon through Forage",
        "softSkills":  "Data Analysis ,Adobe Photoshop ,Lead Generation,MS-OFFICE",
        "cvLink":  "https://drive.google.com/open?id=1cmZ94ZbozQvcuvUZF7ZDEoNPJULRgEL0"
    },
    {
        "id":  10,
        "name":  "Amalu Vijayan",
        "email":  "pg25amalu.vijayan@isbm.ac.in",
        "pgEmail":  "pg25amalu.vijayan@isbm.ac.in",
        "mobile":  "9744681301",
        "rollNo":  "MDP20255045",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  98,
        "perc12":  87,
        "percGrad":  69,
        "gradStreamRaw":  "Arts",
        "gradStream":  "Arts \u0026 Humanities",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Solarsquare",
        "internship1Role":  "Sales intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Social Media Marketing, Digital Marketing, Google Analytics",
        "softSkills":  "Basics of Adobe software, Excel.",
        "cvLink":  "https://drive.google.com/open?id=1PDTT23eF0KlpnUZkpvYdzTxoReTAPFzI"
    },
    {
        "id":  11,
        "name":  "Pallavi Rathore",
        "email":  "pg25pallavi.rathore@isbm.ac.in",
        "pgEmail":  "pg25pallavi.rathore@isbm.ac.in",
        "mobile":  "8640025170",
        "rollNo":  "8.64002517E9",
        "gender":  "Female",
        "section":  "B",
        "aoi":  "Marketing",
        "specialization":  "Human Resources",
        "perc10":  69.5,
        "perc12":  90.6,
        "percGrad":  80,
        "gradStreamRaw":  "Business Administration",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Arcatron Mobility- Frido",
        "internship1Role":  "Retail Operation",
        "internship1Duration":  "6 Months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "3.0",
        "softSkills":  "Team Management,Communication,Problem Solving,Decision Making",
        "cvLink":  "https://drive.google.com/open?id=1Zn7AAqz1RIq65XhcesKv1b-eynZ8-DND"
    },
    {
        "id":  12,
        "name":  "Girish Manohar Patil",
        "email":  "pg25girish.patil@isbm.ac.in",
        "pgEmail":  "pg25girish.patil@isbm.ac.in",
        "mobile":  "8149382908",
        "rollNo":  "M20251230",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  68.8,
        "perc12":  85.17,
        "percGrad":  64.5,
        "gradStreamRaw":  "B Pharmacy",
        "gradStream":  "Science \u0026 Others",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Solarsquare Energy",
        "internship1Role":  "Inside Sales Intern",
        "internship1Duration":  "3 Months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Excel With AI – Office Master (2025) \nPower BI – Office Master (2025)\nProject Management Assessment - Learn Tube (2025)",
        "softSkills":  "Teamwork ,Time management ,Adaptability",
        "cvLink":  "https://drive.google.com/open?id=1WW0LcvJddzAd7Czvnzr672Mzzu-pDSTi"
    },
    {
        "id":  13,
        "name":  "Raushan Bharti",
        "email":  "pg25ruashan.bharti@isbm.ac.in",
        "pgEmail":  "Pg25ruashan.bharti@isbm.ac.in",
        "mobile":  "9162983597",
        "rollNo":  "MNP20251082",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  79,
        "perc12":  66.4,
        "percGrad":  64.87,
        "gradStreamRaw":  "B com accounts honers",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  12,
        "workExpRaw":  "1 yrs",
        "prevJobRole":  "Marketing Executive",
        "internship1Company":  "Kirloskar Brothers ltd",
        "internship1Role":  "Marketing intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "Shree shubh fashion pvt ltd",
        "internship2Role":  "Marketing Executive",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "Yes",
        "softSkills":  "Leadership,  communication,  teamwork ,decision making,  problem solving",
        "cvLink":  "https://drive.google.com/open?id=1YY3NR0p7wwdEiEWmYWwULB9a_R2JhMEO"
    },
    {
        "id":  14,
        "name":  "Aditi kumari",
        "email":  "pg25aditi.kumari@isbm.ac.in",
        "pgEmail":  "pg25aditi.kumari@isbm.ac.in",
        "mobile":  "9693589698",
        "rollNo":  "MNP20251005",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  87.6,
        "perc12":  77.4,
        "percGrad":  80.9,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Urbanic",
        "internship1Role":  "Customer success and experience team intern",
        "internship1Duration":  "5.03.2026-4.05.2026 (2 months)",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Project management from great learning, foundations: data analytics from Coursera, digital marketing from Google.",
        "softSkills":  "Teamwork, critical thinking, problem solving etc",
        "cvLink":  "https://drive.google.com/open?id=1NAFn1HYoaJsr9YzFoc7sHarEFAWXPs-y"
    },
    {
        "id":  15,
        "name":  "Jay Joshi",
        "email":  "pg25jay.joshi@isbm.ac.in",
        "pgEmail":  "pg25jay.joshi@isbm.ac.in",
        "mobile":  "9375015082",
        "rollNo":  "M20251205",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  68,
        "perc12":  64,
        "percGrad":  81.5,
        "gradStreamRaw":  "B.Com",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Burger King",
        "internship1Role":  "Business Development and Operations Intern",
        "internship1Duration":  "Feb 09 - April 09(2 months)",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Google Ads and Digital Marketing in AI( Pursuing)",
        "softSkills":  "Observant , EQ",
        "cvLink":  "https://drive.google.com/open?id=1BbRh-54EKVMZGgbWbkSwj1zLFCrfEv-I"
    },
    {
        "id":  16,
        "name":  "mushkan",
        "email":  "pg25mushkan.singh@isbm.ac.in",
        "pgEmail":  "pg25mushkan.singh@isbm.ac.in",
        "mobile":  "9835364476",
        "rollNo":  "MDP20255029",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  55,
        "perc12":  61.4,
        "percGrad":  70.1,
        "gradStreamRaw":  "marketing ",
        "gradStream":  "Other",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "na",
        "prevJobRole":  "na",
        "internship1Company":  "airattix",
        "internship1Role":  "Product  Development Intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Microsoft excel (intermediate) \nFundamentals of digital marketing",
        "softSkills":  "Problem-Solving\nCommunication Skills\nPresentation Skills\nTeamwork \u0026 Collaboration\nLeadership\nCritical Thinking\nAnalytical Thinking\nTime Management\nAdaptability\nCreativity\nDecision-Making",
        "cvLink":  "https://drive.google.com/open?id=1LVY8pSW1HpE-fn10LdccmVxO-UsmLrm2"
    },
    {
        "id":  17,
        "name":  "Upasak Sharma Choudhury",
        "email":  "pg25upasak.sharma.choudhury@isbm.ac.in",
        "pgEmail":  "pg25upasak.sharma.choudhury@isbm.ac.in",
        "mobile":  "7908415505",
        "rollNo":  "MNP20254016",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  75.6,
        "perc12":  60,
        "percGrad":  74.6,
        "gradStreamRaw":  "CSE(computer science engineering)",
        "gradStream":  "Engineering \u0026 Tech",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "NA",
        "prevJobRole":  "NA",
        "internship1Company":  "Inbody India",
        "internship1Role":  "Sales and marketing intern",
        "internship1Duration":  "4 Months",
        "internship2Company":  "FROUV",
        "internship2Role":  "BDA(buisness development associate)",
        "internship2Duration":  "3 Months",
        "numInternships":  2,
        "certifications":  "Google Digital Marketing \u0026 E-\ncommerce Certificate,\nGoogle Advanced Power BI .",
        "softSkills":  "Critical Thinking, Problem solving, and communication",
        "cvLink":  "https://drive.google.com/open?id=1u6fG8JfcXHP4ctYWdil2UTV5N9uOFBjd"
    },
    {
        "id":  18,
        "name":  "Rishika Ranjan",
        "email":  "pg25rishika.ranjan@isbm.ac.in",
        "pgEmail":  "pg25rishika.ranjan@isbm.ac.in",
        "mobile":  "9199001533",
        "rollNo":  "MNP20254012",
        "gender":  "Female",
        "section":  "A",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  88.6,
        "perc12":  75,
        "percGrad":  82,
        "gradStreamRaw":  "Mathematics ",
        "gradStream":  "Science \u0026 Others",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Airatttix",
        "internship1Role":  "Sales and operation intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Lean Six sigma green belt\nGoogle analytic certification",
        "softSkills":  "Leadership skill\nPresentation skill\nDecision making",
        "cvLink":  "https://drive.google.com/open?id=1W-9t5v8VlXGw7gIEYJfdoSmhxZh93V9o"
    },
    {
        "id":  19,
        "name":  "Harshvardhan Panchal",
        "email":  "pg25harshvardhan.panchal@isbm.ac.in",
        "pgEmail":  "pg25harshvardhan.panchal@isbm.ac.in",
        "mobile":  "9879004611",
        "rollNo":  "MNP20251045",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  81.33,
        "perc12":  79.07,
        "percGrad":  65.3,
        "gradStreamRaw":  "Commerce",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Bajaj Housing Finance",
        "internship1Role":  "Product Intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Leadership, Data Analytics",
        "softSkills":  "Analytical Thinking, Problem Solving, Good Communication, Team Collaboration etc...",
        "cvLink":  "https://drive.google.com/open?id=1vde8HWP55LLn2Tv0BAnjkWOF2-SJcCs2"
    },
    {
        "id":  20,
        "name":  "Dibyajyoti Mohanty",
        "email":  "pg25dibyajyoti.mohanty@isbm.ac.in",
        "pgEmail":  "pg25dibyajyoti.mohanty@isbm.ac.in",
        "mobile":  "8144142255",
        "rollNo":  "MDP20255011",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  99.2,
        "perc12":  77.04,
        "percGrad":  92.62,
        "gradStreamRaw":  "BBA - Marketing ",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "N/A",
        "prevJobRole":  "N/A",
        "internship1Company":  "Pratidin and PratidinTV",
        "internship1Role":  "Marketing Research Intern",
        "internship1Duration":  "1 month",
        "internship2Company":  "BeyondWalls",
        "internship2Role":  "Social Media Marketing",
        "internship2Duration":  "2.5 months",
        "numInternships":  2,
        "certifications":  "1. Google Analytics Certification by Google\n2. Prompt Engineering Certification by Great Learning \n3. Enterprise Design Thinking Practitioner Certification by IBM SkillsBuild\n4. PepsiCo Star Sales Program by PepsiCo",
        "softSkills":  "Brand Communication \nSocial Media Handling \nMeta Business Suite\nCampaign Planning \nEditing (Adobe Photoshop, Illustrator, Canva)\nEvent Management",
        "cvLink":  "https://drive.google.com/open?id=1_9BFHqI3B9Ix74zhYYjRgzpSqRZBnI_4"
    },
    {
        "id":  21,
        "name":  "Anuja Rajesh Gaikwad",
        "email":  "pg25anuja.gaikwad@isbm.ac.in",
        "pgEmail":  "pg25anuja.gaikwad@isbm.ac.in",
        "mobile":  "7977231123",
        "rollNo":  "MDP20255006",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  79.8,
        "perc12":  55.17,
        "percGrad":  80,
        "gradStreamRaw":  "Arts",
        "gradStream":  "Arts \u0026 Humanities",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Burger King",
        "internship1Role":  "Business and Operations Intern",
        "internship1Duration":  "2 months",
        "internship2Company":  "Famous Innovations",
        "internship2Role":  "Client Servicing Intern",
        "internship2Duration":  "2 months",
        "numInternships":  2,
        "certifications":  "Social Media in the Age of Gen AI\nby Udemy\nMeta AI and AI tools by Skill\nNation",
        "softSkills":  "Creative Thinking, Communication, Leadership \u0026 Initiative, Problem-Solving, Adaptability, Team Collaboration, Negotiation \u0026 Persuasion",
        "cvLink":  "https://drive.google.com/open?id=1qgQU8ipqRBlsHhKgfvomDIWZiSgo3zbD"
    },
    {
        "id":  22,
        "name":  "Riya Laxmikant Bahade",
        "email":  "pg25riya.bahade@isbm.ac.in",
        "pgEmail":  "Pg25riya.bahade@isbm.ac.in",
        "mobile":  "9511776148",
        "rollNo":  "M20252209",
        "gender":  "Female",
        "section":  "B",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  72.3,
        "perc12":  72,
        "percGrad":  79,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Workstore pvt ltd.",
        "internship1Role":  "Marketing intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Meta introduction to social media marketing \nMarket research and consumer behavior",
        "softSkills":  "Adaptability, Teamwork, problem solving, perspicacious, leadership,decision making.",
        "cvLink":  "https://drive.google.com/open?id=16UQXNAALKRoHA_Fddode7eovCXQz3tfG"
    },
    {
        "id":  23,
        "name":  "DESHPANDE AKSHATA SACHIN",
        "email":  "pg25akshata.deshpande@isbm.ac.in",
        "pgEmail":  "pg25akshata.deshpande@isbm.ac.in",
        "mobile":  "9370883956",
        "rollNo":  "MNP20252023",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  94.8,
        "perc12":  65.69,
        "percGrad":  67.34,
        "gradStreamRaw":  "B.Tech",
        "gradStream":  "Engineering \u0026 Tech",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "HungerBox",
        "internship1Role":  "Business Development",
        "internship1Duration":  "3 months",
        "internship2Company":  "Prakash Agro Industry",
        "internship2Role":  "Customer Engagement",
        "internship2Duration":  "3 months",
        "numInternships":  2,
        "certifications":  "1. Six Sigma Green Belt – KPMG \n  2. Google Analytics Certification – Google \n3. MS Excel (Intermediate)",
        "softSkills":  "1. Communication\n2. Adaptability\n3. Teamwork",
        "cvLink":  "https://drive.google.com/open?id=1_SSsqjPlmCkGoLYwehjWWs7ioAPnkUoq"
    },
    {
        "id":  24,
        "name":  "Soumilya Barman",
        "email":  "pg25soumilya.barman@isbm.ac.in",
        "pgEmail":  "pg25soumilya.barman@isbm.ac.in",
        "mobile":  "8420512160",
        "rollNo":  "MNP20252086",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  63.33,
        "perc12":  76.17,
        "percGrad":  60.23,
        "gradStreamRaw":  "B. Com",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Bajaj Housing Finance",
        "internship1Role":  "Product Management Intern",
        "internship1Duration":  "27th Jan - 25th April (3 months)",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "SAP FICO, Microsoft Office Intermediate Program, E-Filing on Filing of E-PAN, Income Tax, GST, TDS, Registration of ESIC, EPFO and DSC, CAMBRIDGE UNIVERSITY PRESS SOFT SKILLS \u0026 EMPLOYABILITY SKILLS TRAINING",
        "softSkills":  "Communication, Time Management, Teamwork, Problem Solving",
        "cvLink":  "https://drive.google.com/open?id=1Bvl8ejlexxE5yQ70ojLy9wjMYVVS-Uau"
    },
    {
        "id":  25,
        "name":  "Varsha Kumawat",
        "email":  "pg25varsha.kumawat@isbm.ac.in",
        "pgEmail":  "pg25varsha.kumawat@isbm.ac.in",
        "mobile":  "8291741562",
        "rollNo":  "MDP20255031",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  73.5,
        "perc12":  74.83,
        "percGrad":  74.83,
        "gradStreamRaw":  "BBA Marketing ",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  12,
        "workExpRaw":  "1 year",
        "prevJobRole":  "",
        "internship1Company":  "Bajaj Life Insurance",
        "internship1Role":  "Marketing Intern",
        "internship1Duration":  "6 months",
        "internship2Company":  "Logix Infosecurity",
        "internship2Role":  "Lead generation executive",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "Digital marketers - Udemy",
        "softSkills":  "Communication skills, teamwork and collaboration, leadership",
        "cvLink":  "https://drive.google.com/open?id=1n2sEfg1icPBvbVGB1xqAJBBtzHGE-6PG"
    },
    {
        "id":  26,
        "name":  "Rutuja Bhairu Salokhe",
        "email":  "pg25rutuja.salokhe@isbm.ac.in",
        "pgEmail":  "pg25rutuja.salokhe@isbm.ac.in",
        "mobile":  "7045016343",
        "rollNo":  "MNP20251087",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  80,
        "perc12":  62,
        "percGrad":  80,
        "gradStreamRaw":  "Bachelors in Information Technology",
        "gradStream":  "Engineering \u0026 Tech",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  17,
        "workExpRaw":  "17 months",
        "prevJobRole":  "",
        "internship1Company":  "Kantar",
        "internship1Role":  "Market Research",
        "internship1Duration":  "3 months",
        "internship2Company":  "Deloitte USI",
        "internship2Role":  "IT and Associate Analyt",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "MS Excel by Linkedin\nMS Powerpoint by Linkedin\nBusiness Analyst: Software Testing Processes \u0026 Techniques - Udemy",
        "softSkills":  "Management skills\nAnalytical thinking\nPresentation Skills",
        "cvLink":  "https://drive.google.com/open?id=1g3NiQtYiEDb1aSu7tq1LLpC-ZhFI0uUe"
    },
    {
        "id":  27,
        "name":  "Rishik Paul",
        "email":  "pg25rishik.paul@isbm.ac.in",
        "pgEmail":  "pg25rishik.paul@isbm.ac.in",
        "mobile":  "8969264800",
        "rollNo":  "MDP20255042",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  77.8,
        "perc12":  57.6,
        "percGrad":  63,
        "gradStreamRaw":  "B.COM(hons)",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Propedge Realty",
        "internship1Role":  "Business Development Intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Finlatics",
        "softSkills":  "Client Acquisition \u0026 KYC Onboarding ,Insurance \u0026 Financial Product Knowledge,Excel \u0026 Google Sheets (Pivot Tables, Dashboards",
        "cvLink":  "https://drive.google.com/open?id=1hW-HHrCnihns64j17xlOVtitie6c0PQm"
    },
    {
        "id":  28,
        "name":  "Sunay Singh",
        "email":  "pg25sunay.singh@isbm.ac.in",
        "pgEmail":  "pg25sunay.singh@isbm.ac.in",
        "mobile":  "6266981352",
        "rollNo":  "MDP20255043",
        "gender":  "Male",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  81.6,
        "perc12":  74.3,
        "percGrad":  85,
        "gradStreamRaw":  "Hospitality ",
        "gradStream":  "Science \u0026 Others",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  10,
        "workExpRaw":  "10 months",
        "prevJobRole":  "Dessert chef",
        "internship1Company":  "Beardo (Marico Ltd.)",
        "internship1Role":  "Sales trainee",
        "internship1Duration":  "2 months",
        "internship2Company":  "Thrive Realty Partners",
        "internship2Role":  "Branding intern",
        "internship2Duration":  "3 months",
        "numInternships":  2,
        "certifications":  "Google analytics.",
        "softSkills":  "Communication, strategic thinking, adaptability, team collaboration, leadership and orientation.",
        "cvLink":  "https://drive.google.com/open?id=1x11GPz3yktdCYpYVR6AwWsvUJo8hzh6l"
    },
    {
        "id":  29,
        "name":  "Udai Pratap Singh",
        "email":  "pg25udai.pratap.singh@isbm.ac.in",
        "pgEmail":  "pg25udai.pratap.singh@isbm.ac.in",
        "mobile":  "9660865497",
        "rollNo":  "MDP20255029",
        "gender":  "Male",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  66.5,
        "perc12":  63,
        "percGrad":  70.58,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  9,
        "workExpRaw":  "9 months",
        "prevJobRole":  "",
        "internship1Company":  "Thrive Realty Partners",
        "internship1Role":  "Digital marketing intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "India mart , TheConnecteursocio",
        "internship2Role":  "Social media executive",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "Meta blueprint , GA4",
        "softSkills":  "Adaptblity , communication",
        "cvLink":  "https://drive.google.com/open?id=17Mnuj_hL9omlaOmvSO6y6SshzfYrnYy-"
    },
    {
        "id":  30,
        "name":  "Shailee Sarraf",
        "email":  "pg25shailee.sarraf@isbm.ac.in",
        "pgEmail":  "pg25shailee.sarraf@isbm.ac.in",
        "mobile":  "8603337089",
        "rollNo":  "MNP20252073",
        "gender":  "Female",
        "section":  "A",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  78.3,
        "perc12":  92.4,
        "percGrad":  88.1,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Godrej Properties",
        "internship1Role":  "Marketing and Sales",
        "internship1Duration":  "2 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Skill Nation",
        "softSkills":  "Communication skills, Problem-solving,",
        "cvLink":  "https://drive.google.com/open?id=16tQzz5cG3myg33jL8Yj82UZw-NzbahRF"
    },
    {
        "id":  31,
        "name":  "Bristi Ghosh",
        "email":  "pg25bristi.ghosh@isbm.ac.in",
        "pgEmail":  "pg25bristi.ghosh@isbm.ac.in",
        "mobile":  "9832333588",
        "rollNo":  "MNP20251030",
        "gender":  "Female",
        "section":  "B",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  67,
        "perc12":  95,
        "percGrad":  70,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "NA",
        "prevJobRole":  "NA",
        "internship1Company":  "Star Estate",
        "internship1Role":  "Channel partner intern",
        "internship1Duration":  "10 th January to 30 March, 2026",
        "internship2Company":  "",
        "internship2Role":  "NA",
        "internship2Duration":  "NA",
        "numInternships":  1,
        "certifications":  "MS excel certificate, Data visualization certificate.",
        "softSkills":  "Communication, problem solving, Team work.",
        "cvLink":  "https://drive.google.com/open?id=1XkMfNyrBcIlAldqLcUTYyQ3Pf2fUcqe3"
    },
    {
        "id":  32,
        "name":  "Gurleen Kaur Virk",
        "email":  "pg25gurleen.kaur@isbm.ac.in",
        "pgEmail":  "pg25gurleen.kaur@isbm.ac.in",
        "mobile":  "8103422284",
        "rollNo":  "MNP20251129",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "LSCM",
        "perc10":  95,
        "perc12":  85,
        "percGrad":  65.8,
        "gradStreamRaw":  "Science ",
        "gradStream":  "Science \u0026 Others",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Work Store Pvt Ltd",
        "internship1Role":  "SEO and Digital Marketing Intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "AI career acceleration program, AI tools workshop certificate, GA 4 Certificate, Digital Marketing certificate, Diploma in Office Automation.",
        "softSkills":  "Communication, Adaptability, stakeholder management, emotional intelligence, analytical thinking, collaboration \u0026 teamwork.",
        "cvLink":  "https://drive.google.com/open?id=1QtKJn9zaZe24Bo--QVJMwr_U7ljtpHhi"
    },
    {
        "id":  33,
        "name":  "Subhojeet Sarkar",
        "email":  "pg25subhojeet.sarkar@isbm.ac.in",
        "pgEmail":  "pg25subhojeet.sarkar@isbm.ac.in",
        "mobile":  "6201081204",
        "rollNo":  "MNP20251117",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  75,
        "perc12":  81,
        "percGrad":  70,
        "gradStreamRaw":  "Bachelor of business administration ",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  true,
        "workExpMonths":  11,
        "workExpRaw":  "11months",
        "prevJobRole":  "It was of to creating business opportunities for the company through varied market research and customer understanding.",
        "internship1Company":  "Inbody India",
        "internship1Role":  "Marketing intern",
        "internship1Duration":  "4 months",
        "internship2Company":  "Codeyoung Pvt Ltd",
        "internship2Role":  "Business developer",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "Social Media Marketing Course (udemy)\nFundamentals of Digital marketing Course",
        "softSkills":  "Problem solving \nManagement skills",
        "cvLink":  "https://drive.google.com/open?id=1coyQLAhQH2LQutc-gCdVZkyWNSxWyUML"
    },
    {
        "id":  34,
        "name":  "Parve Maheshwari",
        "email":  "pg25parve.maheshwari@isbm.ac.in",
        "pgEmail":  "pg25parve.maheshwari@isbm.ac.in",
        "mobile":  "7976661770",
        "rollNo":  "M20251211",
        "gender":  "Male",
        "section":  "B",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  82.8,
        "perc12":  94.6,
        "percGrad":  58.55,
        "gradStreamRaw":  "BCOM",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Inbody India",
        "internship1Role":  "Digital Marketing and Event Coordination",
        "internship1Duration":  "4 Months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "1. Meta (Introduction to Social \nMedia Marketing) (2024) \n2. Foundation of Digital \nMarketing and E-Commerce \n(2025) \n3. Google Analytics \nCertification (GA4) - Google \nSkill shop (2026)",
        "softSkills":  "1. Management skills \n2. Microsoft Office \n3. Analytical thinking \n4. Leadership \n5. Project Management \n6. Communication skills \n7. Team collaboration",
        "cvLink":  "https://drive.google.com/open?id=12AeGJkligq1safOEHicqGocNYpX4PUha"
    },
    {
        "id":  35,
        "name":  "Akshat Malav",
        "email":  "pg25akshat.malav@isbm.ac.in",
        "pgEmail":  "Pg25akshat.malav@isbm.ac.in",
        "mobile":  "9414454248",
        "rollNo":  "MNP20251008",
        "gender":  "Male",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  60.5,
        "perc12":  63.2,
        "percGrad":  67.5,
        "gradStreamRaw":  "Marketing ",
        "gradStream":  "Other",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Burgerking",
        "internship1Role":  "Maketing intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "VJ Analytics",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  2,
        "certifications":  "Excel: by Udemy (Pursuing)\nDigital Marketing Certification – Interns Elite (2025)\nDigital Marketing Internship – VJ Analytics\nGoogle Analytics - Google Skill Shop",
        "softSkills":  "MS-OFFICE\nDigital Marketing\nCRM Skills\nCritical Thinking\nTask Delegation\nProject Management\nTeamwork \u0026 Collaboration",
        "cvLink":  "https://drive.google.com/open?id=1r78nsMa09trSw4eiZiMA-FbqA5UrQN--"
    },
    {
        "id":  36,
        "name":  "Stuti Sharma",
        "email":  "pg25stuti.sharma@isbm.ac.in",
        "pgEmail":  "pg25stuti.sharma@isbm.ac.in",
        "mobile":  "6367220158",
        "rollNo":  "MDP20255412",
        "gender":  "Female",
        "section":  "E",
        "aoi":  "Marketing",
        "specialization":  "Media",
        "perc10":  78.8,
        "perc12":  92.4,
        "percGrad":  63.9,
        "gradStreamRaw":  "BA (English Literature + French)",
        "gradStream":  "Arts \u0026 Humanities",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Viral Fission",
        "internship1Role":  "Content Production and Creation Intern",
        "internship1Duration":  "3 Months",
        "internship2Company":  "Solar Square",
        "internship2Role":  "Pre/Inside Sales Intern",
        "internship2Duration":  "3 Months",
        "numInternships":  2,
        "certifications":  "Google Analytics 4 (GA4)\nCertification – Google SkillShop",
        "softSkills":  "Management skills\nContent Creation\n Social Media Writing\n French (Intermediate)\nPhotoshop (Beginning)\n Photography (Basic)\nCritical Communication",
        "cvLink":  "https://drive.google.com/open?id=1rqDCg2RYugAOfJfvoZ0QD_NLQ9sbPJHz"
    },
    {
        "id":  37,
        "name":  "Aryan Raj",
        "email":  "pg25aryan.raj@isbm.ac.in",
        "pgEmail":  "pg25aryan.raj@isbm.ac.in",
        "mobile":  "6206544550",
        "rollNo":  "MNP20251022",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  60,
        "perc12":  71,
        "percGrad":  64,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Star Estate",
        "internship1Role":  "Pre sales",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "› Digital Marketing and E-Commerce by Google\n› Infosys Springboard Young Industry Enthusiast – Retail\n› Google Analytics 4\n› Financial Literacy",
        "softSkills":  "Effective Communication\nTeamwork \u0026 Collaboration\nProblem-Solving \u0026 Decision-Making\nAdaptability \u0026 Quick Learning\nTime Management \u0026 Leadership",
        "cvLink":  "https://drive.google.com/open?id=1JEWyxdZ-r8O1pTBRJR5qEbwiodLkpnfY"
    },
    {
        "id":  38,
        "name":  "Vaishnavi Agarwal",
        "email":  "pg25vaishnavi.agrawal@isbm.ac.in",
        "pgEmail":  "pg25vaishnavi.agrawal@isbm.ac.in",
        "mobile":  "9570871510",
        "rollNo":  "M20251219",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  75,
        "perc12":  75,
        "percGrad":  61,
        "gradStreamRaw":  "Commerce",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Purnartha Investment",
        "internship1Role":  "Sales \u0026 Marketing Intern",
        "internship1Duration":  "2 months",
        "internship2Company":  "Tata Steel Ltd.",
        "internship2Role":  "Sales \u0026 Marketing Intern / Vocational Trainee",
        "internship2Duration":  "5 weeks",
        "numInternships":  2,
        "certifications":  "DCA and GOOGLE Analytics",
        "softSkills":  "Active Listening, CRM, Relationship Building, Teamwork, communication",
        "cvLink":  "https://drive.google.com/open?id=1G8uQ5G4ZIGQqv6NNUvjmiEU1FmC0T2g5"
    },
    {
        "id":  39,
        "name":  "Priyansh Mishra",
        "email":  "pg25priyansh.mishra@isbm.ac.in",
        "pgEmail":  "Pg25priyansh.mishra@isbm.ac.in",
        "mobile":  "7620988508",
        "rollNo":  "MDP20255021",
        "gender":  "Male",
        "section":  "C",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  77.4,
        "perc12":  87.17,
        "percGrad":  75.24,
        "gradStreamRaw":  "BBA",
        "gradStream":  "Management (BBA)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Maestro Realtek",
        "internship1Role":  "Pre sale intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "My Ev service",
        "internship2Role":  "Business development intern",
        "internship2Duration":  "3 months",
        "numInternships":  2,
        "certifications":  "Ms Excel",
        "softSkills":  "B2B Business Development\n Franchise Sales\n Lead Generation\n Social Media Marketing\n Content Creation\n Pitch Deck Development\n Market Research\n Canva\n MS PowerPoint \u0026 Excel",
        "cvLink":  "https://drive.google.com/open?id=1xPbDzVhoIX7lKmlC5yOVAS_hXcJSOtOS"
    },
    {
        "id":  40,
        "name":  "Ved Shandilya",
        "email":  "pg25ved.shandilya@isbm.ac.in",
        "pgEmail":  "pg25ved.shandilya@isbm.ac.in",
        "mobile":  "9302190329",
        "rollNo":  "MNP20251110",
        "gender":  "Male",
        "section":  "A",
        "aoi":  "Marketing",
        "specialization":  "Business Analytics",
        "perc10":  86,
        "perc12":  76,
        "percGrad":  66,
        "gradStreamRaw":  "Commerce ",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Rentickle",
        "internship1Role":  "Digital Marketing Intern",
        "internship1Duration":  "3 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "Introduction to MS Excel, Fundamentals of Digital Marketing, Content and Social Media Marketing",
        "softSkills":  "Event management, Creative Thinking, Team Player, Leadership Skills",
        "cvLink":  "https://drive.google.com/open?id=1wCOCOtXoTwTS_XMMkPvTXZGfvRm-PB5V"
    },
    {
        "id":  41,
        "name":  "Anshika Purohit",
        "email":  "pg25anshika.purohit@isbm.ac.in",
        "pgEmail":  "pg25anshika.purohit@isbm.ac.in",
        "mobile":  "8303720300",
        "rollNo":  "MNP20252015",
        "gender":  "Female",
        "section":  "A",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  69,
        "perc12":  84,
        "percGrad":  72.2,
        "gradStreamRaw":  "Commerce ( B.Com )",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Inbody India",
        "internship1Role":  "Sales Intern",
        "internship1Duration":  "4 months",
        "internship2Company":  "",
        "internship2Role":  "",
        "internship2Duration":  "",
        "numInternships":  1,
        "certifications":  "MS Excel (Intermediate) \n— Udemy\n➢ Strategy Consulting — \nAccenture (Forage)\n➢ Generative AI for All — \nInfosys\n➢ Listing of Security Stock\nExchange — NISM\n➢ Automated Digital \nMarketing \u0026 Social \nMedia with Generative \nAI — Udemy\n➢ Power BI — SimplilearnPower BI",
        "softSkills":  "Power BI\n➢ Excel (Intermediate)\n➢ Analytical Thinking\n➢ Canva Basics\n➢ B2B Sales \u0026 Lead \nGeneration\n➢ Customer Engagement \u0026\nProduct Demonstration\n➢ CRM \u0026 Sales Pipeline \nManagement",
        "cvLink":  "https://drive.google.com/open?id=1o8fbEviKn0KM_isFJIwXc6yrPIHnsnQt"
    },
    {
        "id":  42,
        "name":  "Muskan Ahirwar",
        "email":  "pg25muskan.ahirwar@isbm.ac.in",
        "pgEmail":  "Pg25muskan.ahirwar@isbm.ac.in",
        "mobile":  "8303221042",
        "rollNo":  "MNP20251063",
        "gender":  "Female",
        "section":  "D",
        "aoi":  "Marketing",
        "specialization":  "Finance",
        "perc10":  70.81,
        "perc12":  81,
        "percGrad":  68.72,
        "gradStreamRaw":  "Commerce ",
        "gradStream":  "Commerce (B.Com)",
        "gradUniversity":  "",
        "hasWorkExp":  false,
        "workExpMonths":  0,
        "workExpRaw":  "None",
        "prevJobRole":  "",
        "internship1Company":  "Godrej Properties",
        "internship1Role":  "Channel sales and marketing",
        "internship1Duration":  "2 months",
        "internship2Company":  "",
        "internship2Role":  "NA",
        "internship2Duration":  "NA",
        "numInternships":  1,
        "certifications":  "Advance excel, generative ai , social media marketing",
        "softSkills":  "Crm, communication, analytical thinking,",
        "cvLink":  "https://drive.google.com/open?id=19_ue8SptTOG1vk3qdUgO81-GKVeriQoA"
    }
];
if (typeof module !== 'undefined' && module.exports) { module.exports = INITIAL_BATCH_DATA; }

